---
- name: install squid package
  yum:
    name: squid
    state: latest

- name: start squid service
  service:
    name: squid
    state: started
    enabled: yes
  
- name: Check access.log file
  stat:
    path: /var/log/squid/access.log
  register: file

- debug:
    msg: "access.log is created"
  when: file.stat.exists == true

#########NIFI Installation
#
#
#- name: Download nifi Package
#  get_url:
#    url: http://www-us.apache.org/dist/nifi/1.3.0/nifi-1.3.0-bin.zip
#    dest: /usr/lib/nifi-1.3.0-bin.zip

- name: Unzip the downloaded file
  command: unzip nifi-1.3.0-bin.zip
  args:
    chdir: /usr/lib
  ignore_errors: yes
#  unarchive:
#    src: /usr/lib/nifi-1.3.0-bin.zip
#    dest: /usr/lib
#    remote_src: yes

- name: Change the Port Number 
  lineinfile:
    dest: /usr/lib/nifi-1.3.0/conf/nifi.properties
    regexp: '^nifi.web.http.port'
    line: 'nifi.web.http.port={{nifi_port}}'

- name: Install Nifi
  command: /usr/lib/nifi-1.3.0/bin/nifi.sh install nifi

- name: Disable Firewall
  service:
    name: firewalld
    state: stopped

- name: making entries in hosts file
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.name }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
  with_items:
    - { name: '{{ nifi_hostname }}', ip: '{{ nifi_ip }}' }
    - { name: '127.0.0.1', ip: 'localhost' }
 
- name: installing java packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ java_pkgs }}"

- name: set path for java
  shell: export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s_/jre/bin/java__")

- name: set path for java for future reboots
  lineinfile:
    path: /etc/profile.d/java_18.sh
    line: 'export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s_/jre/bin/java__")'
    state: present
    create: yes
    mode: 0777

- name: source the java file
  shell: source /etc/profile.d/java_18.sh

- name: Start the nifi Service
  command: service nifi start
