---
- name: set ulimit
  shell: ulimit -n 32768

- name: set ulimit
  shell: ulimit -u 65536

- name: Adjust limits to secure level
  lineinfile:
    path: /etc/security/limits.conf
    state: present
    line: "{{ item.line }}"
  with_items:
    - { line: '* - nofile 32768' }
    - { line: '* - nproc 65536' }
