---
- name: Installing JAVA
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
  - "{{ java_pkgs }}"

- name: setting path to java 8
  shell: export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s_/jre/bin/java__")

- name: setting path for future reboots
  lineinfile:
    path: /etc/profile.d/java_18.sh
    line: 'export JAVA_HOME=$(readlink -f /usr/bin/java | sed "s_/jre/bin/java__")'
    state: present
    create: yes
    mode: 0777

- name: source the java file
  shell: source /etc/profile.d/java_18.sh

- name: downloading maven file
  get_url:
    url: http://apache.volia.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
    dest: /tmp/apache-maven-3.3.9-bin.tar.gz

- name: Extracting tar file of maven
  command: tar -zxf /tmp/apache-maven-3.3.9-bin.tar.gz -C /opt/
#  unarchive:
#    src: /tmp/apache-maven-3.3.9-bin.tar.gz
#    dest: /opt/apache-maven-3.3.9-bin
#    remote_src: yes

- name: setting path for maven
  shell: PATH=/opt/apache-maven-3.3.9/bin:$PATH

- name: making entries for maven
  lineinfile:
    path: /etc/profile.d/maven.sh
    line: 'export PATH=/opt/apache-maven-3.3.9/bin:$PATH'
    mode: 0777
    create: yes

- name: source the maven
  shell: source /etc/profile.d/maven.sh
