---
# If we excute below code, system will not reboot properly

#- name: change the line
#  lineinfile:
#    path: /etc/default/grub
#    state: present
#    regexp: '^GRUB_CMDLINE_LINUX'
#    line: 'GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=cl/root rd.lvm.lv=cl/swap rhgb quiet transparent_hugepage=never"'

#- name: configuring grub
#  command: grub2-mkconfig -o /boot/grub2/grub.cfg
#

# altenative way
#
- name: copying files to hadoop node2
  copy:
    src: disable-thp.service
    dest: /etc/systemd/system/disable-thp.service

- name: just force systemd to reread configs
  systemd:
    name: disable-thp
    state: started
    enabled: yes
    daemon_reload: yes

- name: start the disable-thp service
  service:
    name: disable-thp
    state: started
    enabled: yes

- name: disabling selinux policy
  selinux:
    state: disabled
