---
- name: enable time sync
  service:
    name: ntpd
    state: started
    enabled: yes

- name: disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: disable selinux
  selinux:
    state: disabled
